name: 'Aruns Composite Action'
description: 'My first composite action function'

inputs:
  name: 
    description: 'Name of the Person'
    required: true
    default: 'this_is_default_name'

outputs:
  random-number:
    description: "The random number"
    value: ${{ steps.random.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - name: Step1
      run: echo Hello ${{ inputs.name }}
      shell: bash
    - name: Step2
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      id: random
      shell: bash
    - name: Step3 
      id: python-addition
      run: |
        import sys
        num1 = 1
        num2 = 2
        sum = num1 + num2
        print (sum)
      shell: python
    - name: Step4
      uses: actions/github-script@v4
      id: set-result
      with:
       script: return "Hello!"
       result-encoding: string
