name: 'Aruns Composite Action'
description: 'My first composite action function'

inputs:
  name: 
    description: 'Name of the Person'
    required: true
    default: 'this_is_default_name'

outputs:
  random-number:
    description: "The random number"
    value: ${{ steps.random.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.name }}
      shell: bash
    - run: echo "::set-output name=random-id::$(echo $RANDOM)"
      id: random
      shell: bash
