on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Greet
        id: foo
        uses: arunanandhan/hello-world-composite-run-steps-action@main
        with:
          who-to-greet: 'Arun Anand'
      - name: Random
        run: echo random-number is ${{ steps.foo.outputs.random-number }}
        shell: bash
