name: 'Aruns Composite Workflow'

on: 
  push:
    branches: [ main ]

env:
  key1: 'This is workflow env variable'

jobs: 
  Init-Job:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.set-result.outputs.ref }}
    steps:
     - name: Step1
       uses: actions/github-script@v4
       id: set-result
       with:
         script: |
           var ref = '123'
           console.log("ref: ", "Hello!" )
           return ref
         result-encoding: string
    
  First-Job:
    needs: Init-Job
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
       - name: Step1
         uses: actions/checkout@v2
         with:
           ref: ${{ needs.Init-Job.outputs.ref }}
       - name: First-Step
         run: pwd
       - name: Step2
         id: action-file
         uses: ./.github/actions/module
         with:
           name: "Arunkumar Anandhan"
       - name: Step3
         run: |
           echo ${{ steps.action-file.outputs.random-number }}
       - name: Step4
         run: |
           echo $ref
         


         
