name: 'Aruns Composite Workflow'

on: 
  push:
    branches: [ main ]

env:
  Location: 'Utah'

jobs:  
  Main-Dependency-Job:
    runs-on: windows-latest
    steps:
      - name: Step1
        run: |
          pwd
          dir
  First-Job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
       - name: Step1
         uses: actions/checkout@v2
       - name: First-Step
         run: pwd
       - name: Step2
         id: action-file
         uses: ./.github/actions/module
         with:
           name: "Arunkumar Anandhan"
       - name: Step3
         run: |
           echo ${{ steps.action-file.outputs.random-number }}
       - name: Step4
         run:
           echo "My Location is $Location"
           
         
