name: 'Aruns Composite Workflow'

on: 
  push:
    branches: [ main ]

env:
  key1: 'This is workflow env variable'

jobs: 
  First-Job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    steps:
       - name: Initial-Step
         uses: actions/checkout@v2
       - name: First-Step
         run: pwd
       - name: Second-Step
         id: action-file
         uses: ./.github/actions/module
         with:
           name: "Arunkumar Anandhan"
       - name: Third-Step
         run: |
           echo ${{ steps.action-file.outputs.random-number }}
       - name: Fourth-Step
         run: |
           echo $key1

         
