name: 'Aruns Composite Workflow'

on: 
  push:
    branches: [ main ]

env:
  key1: 'This is workflow env variable'

jobs: 
  First-Job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    steps:
       - name: Step1
         uses: actions/checkout@v2
       - name: First-Step
         run: pwd
       - name: Step2
         id: action-file
         uses: ./.github/actions/module
         with:
           name: "Arunkumar Anandhan"
       - name: Step3
         run: |
           echo ${{ steps.action-file.outputs.random-number }}
       - name: Step4
         uses: actions/github-script@v4
         id: set-result
         with:
          script: return "Hello!"
          result-encoding: string

         
